manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim 
    - name: smoes
      url-base: https://github.com/smoes 
  projects:
    - name: zmk
      remote: infused-kim
      revision: pr-testing/mouse_ps2_module_base
      import: app/west.yml
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: smoes
      revision: main
  self:
    path: config
